//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lanpuda.Client.Theme.Localizations {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lanpuda.Client.Theme.Localizations.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 添加行 的本地化字符串。
        /// </summary>
        public static string UI_AddRow {
            get {
                return ResourceManager.GetString("UI_AddRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 批量新建 的本地化字符串。
        /// </summary>
        public static string UI_BatchCreate {
            get {
                return ResourceManager.GetString("UI_BatchCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        public static string UI_Close {
            get {
                return ResourceManager.GetString("UI_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认删除吗？删除后无法恢复！ 的本地化字符串。
        /// </summary>
        public static string UI_ConfirmDelete {
            get {
                return ResourceManager.GetString("UI_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 条/页 的本地化字符串。
        /// </summary>
        public static string UI_Count_PerPage {
            get {
                return ResourceManager.GetString("UI_Count_PerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建 的本地化字符串。
        /// </summary>
        public static string UI_Create {
            get {
                return ResourceManager.GetString("UI_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public static string UI_Delete {
            get {
                return ResourceManager.GetString("UI_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除行 的本地化字符串。
        /// </summary>
        public static string UI_DeleteRow {
            get {
                return ResourceManager.GetString("UI_DeleteRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑 的本地化字符串。
        /// </summary>
        public static string UI_Edit {
            get {
                return ResourceManager.GetString("UI_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打印 的本地化字符串。
        /// </summary>
        public static string UI_Print {
            get {
                return ResourceManager.GetString("UI_Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询 的本地化字符串。
        /// </summary>
        public static string UI_Query {
            get {
                return ResourceManager.GetString("UI_Query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重置 的本地化字符串。
        /// </summary>
        public static string UI_Reset {
            get {
                return ResourceManager.GetString("UI_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        public static string UI_Save {
            get {
                return ResourceManager.GetString("UI_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作成功 的本地化字符串。
        /// </summary>
        public static string UI_Successful {
            get {
                return ResourceManager.GetString("UI_Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 警告！ 的本地化字符串。
        /// </summary>
        public static string UI_Warning {
            get {
                return ResourceManager.GetString("UI_Warning", resourceCulture);
            }
        }
    }
}
